### ISSUE TITLE
Mobile app

### ISSUE THREAD

**Issue by kareniel** [job-talk/dhammapuja#32]
I started working on a meditation mobile app; basically a timer that keeps a history of your sessions. I wanted to include a chanting section but then I realized that you are actively working on this project. I could simply fork your repo and go to town but I wanted to leave a note here; I would love to collaborate with other devs who also study & practice Dhamma. :)

**Comment by job-talk** [comment]
Feel free to fork or to work here in this repo.

I would be happy to help and collaborate with you. My scripting/programming skills are quite young at the moment so I'm not sure how much help I would be.

**Comment by kareniel** [comment]
Sweet! I'll check out the issues and see if there's something I can easily contribute.

By the way, I don't know what your goals are with respect to learning programming, but if there's any way I can help you, feel free to ask, I will be more than happy to oblige. 

ps: I used dhammapuja.com for chanting today! It was very helpful.

**Comment by job-talk** [comment]
I'm happy that you were able to make use of it!

I'm trying to learn general frontend development and design. Thanks, I'll be sure to let you know if any questions may arise :)
